---
- name: play to demonstrate lineinfile module
  hosts: localhost
  become: true
  remote_user: ansible
  tasks:
   - name: insert a line before the given pattern matching text
     lineinfile:
      path: /etc/ssh/sshd_config
      insertafter: ^PermitRootLogin
      line: "#the above line tells if root is allowed to login"
      backup: yes
      state: present
...      
