---
- name: play to set hostname
  hosts: 192.168.5.44
  remote_user: ansible
  become: true
  gather_facts: no
  tasks:
   - name: set hostname
     hostname:   #hostname module is used o set the hostname
      name: lokiEngine.alclabs.in
...      