---
- name: Play to demonstrate archieve
  hosts: [192.168.5.66 192.168.5.44]
  become: true
  remote_user: ansible
  tasks: 
   - name: Task to archieve remote server /etc
     archive:
      path: /etc
      dest: /tmp/etc_archive.tar.gz
      format: gz
      owner: ansible
      group: ansible
      mode: 0600
...      

      
