---
- name: play to demonstrate magic groups variable
#commonly used magic variables
#hostvars: you can access variables defined by any host in the play
#groups: print the dictionary or map with all groups in inventory and each group has the elise
#group_name: List groups the current host is part of
#inventory_hostname: inventory name of current host being iterated over in the play
  hosts: 192.168.5.66
  become: true
  remote_user: ansible
  tasks:
   - name: print the hostgroup
     debug:
      var: groups
   - name: print group_names
     debug:
      var: group_names
   - name: print inventory_hostname
     debug:
      var: inventory_hostname
   - name: print hostvars
     debug:
      var: hostvars
...         

