---
- name: Demonstrate include_vars
  hosts: localhost
  become: true
  remote_user: ansible
  tasks:
   - name: Include the variables defined compute.yml
     include_vars: vars/compute.yml
   - name: print the variabvles
     debug:
      msg: "valus are city: {{city}} and country: {{country}}" 
...      