---
- name: create users
  hosts: localhost
  become: true
  remote_user: ansible
  vars:
   u_name: rolex
  tasks:
   - name: create a user
     user:
      name: "{{u_name}}"
      password: "{{u_name|password_hash}}"
      comment: "user {{u_name}} to adminster" 
     register: out
   - name: print debug output
     debug:
      var: out 
...    