---
- name: disable direct root logins using ssh
  hosts: tiger
  become: true
  remote_user: ansible
  tasks:
   - name: Task to modify (replace) permit root logins in /etc/ssh/sshd_config file
     replace: 
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin no'
      replace: 'PermitRootLogin yes'
      backup: yes
   - name: Restart sshd daemon after changing conf file
     service: 
      name: sshd
      state: restarted
...         