---
- name: Work with module that fails
  hosts: localhost
  remote_user: ansible
  become: true
  vars:
   u_name: op01
  tasks:
   - name: create a user
     user:
      name: "{{u_name}}"
      password: "{{u_name|password_hash}}"
      uid: "{{u_id}}" # read this variable from command line provided as extra variable
      update_password: on_create
     register: out 
     ignore_errors: yes  
   - name: print me at the end of the play
     debug:
      msg: "unable to create {{u_name}}"
     when: out.failed
...          