---
- name: play to modify selinux in /etc/selinux/config file
  hosts: localhost
  become: true
  become_user: root
  remote_user: ansible
  tasks:
   - name: Task to edit selinux config file
     lineinfile:
      path: /etc/selinux/config
      regexp: ^SELINUX=
      line: "SELINUX=disabled"