---
- name: play to implement pause module
  hosts: localhost
  gather_facts: false
  remote_user: ansible
  become: true
  vars:
   wait_time: 10
  tasks:
   - name: print the  message before {{wait_time}} waiting seconds
     debug:
      msg: Hi I am here before you {{wait_time}} seconds
   - name: Task to check the pause module
     pause: 
      seconds: "{{wait_time}}"
   - name: print the message after {{wait_time}} seconds
     debug:
      msg: Hi I am here after {{wait_time}}  seconds     