#Ansible playbook can have multiple plays. This playbook demonstrate
#Multiple plays in a single playbook
---
- name: Play1 - Install smb
  hosts: [192.168.5.66 192.168.5.44]
  remote_user: ansible
  become: true
  tasks:
   - name: Task to install samba server package
     yum:
      name: samba
      state: latest
#End of the first play
#Beginning of the second play
- name: Play2 - Start samba services
  hosts: [192.168.5.66 192.168.5.44]
  remote_user: ansible
  become: true
  tasks:
   - name: Task1 - Start smbd
     service:
      name: smb
      state: started
   - name: Task2 - start nmbd
     service:
      name: nmb
      state: started
#End of the play2
...              
