---
- name: play to create a group and then user
  hosts: localhost
  remote_user: ansible
  become: true
  tasks: 
   - name: Task to create a group
     group: 
      name: vandanaops
      state: present
   - name: Create a user and make devops as suppliment group
     user:
      name: vandudm01
      password: $6$vghfhstffg$vlWZJKi6srgshVS2SvTff0GXpWicFspgiEPPsYtyAhKEQV.Q.qE.QLWAAEwSuOau6pRyfDBdzaUAVrrGMdTiD1
      shell: /bin/bash
      uid: 7654
      groups: vandanaops
      comment: "Created for ansible administration by Ansible Engine"
      home: /home/vandudm01
...