---
- name: Demonstrate debug module
  hosts: localhost
  become: true
  remote_user: ansible
  vars:
   OS: Linux
  vars_files:  vars/compute.yml
   # - vars/compute.yml
  tasks:
   - name: Task to print the text on the screen
     debug:
      msg: "Good Evening... its Ansible..and its {{OS}}  {{city}} {{country}} Intelligent!!!"
...    
