---
- name: play to modify selinux in /etc/selinux/config file
  hosts: localhost
  become: true
  become_user: root
  become_user: ansible
  tasks:
   - name: Task to edit selinux config file
     lineinfile:
      path: /etc/hosts
      line: "192.168.1.25   vcenter.alclabs.in \n 192.168.1.20  gateway.alclabs.in" #appends
...     