---
- name: create a group
  hosts: localhost
  become: true
  remote_user: ansible
  vars:
   grpname: dbgroup
   usrname: dbadm01
   usr_pass: var/sec1.yml #abc123
  tasks:
   - name: create a group {{grpname}} which will be used as secondary groups for another user
     group:
      name: "{{grpname}}" 
      state: present
   - name: create a user {{username}} with secondary group dbgroup
     user:
      name: "{{usrname}}"
      password: "{{usr_pass| password_hash('sha512')}}" 
      update_password: on_create
      groups: dbgroup
      state: present
...       

